# ===============================
# GENERAL APPLICATION SETTINGS
# ===============================

spring.application.name=neo-price-api

spring.jpa.open-in-view=false

# ===============================
# JPA / HIBERNATE SETTINGS
# ===============================

spring.jpa.show-sql=false

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=update

# ===============================
# DATABASE SETTINGS
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/neoprice
spring.datasource.username=postgres
spring.datasource.password=postgre123

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JSON SETTINGS
# ===============================

spring.jackson.time-zone=America/Sao_Paulo

# ===============================
# ERROR HANDLING
# ===============================

server.error.include-message=always